// Package codegen generates C source code from a Monk AST.
//
// The generated C #includes runtime.h and calls runtime functions for
// all Monk operations. The output is a complete, compilable .c file.
package codegen

import (
	"fmt"
	"strings"

	"github.com/monkfromearth/monk-lang/syntax"
)

// Generate takes a parsed Monk program and returns a complete C source string.
// The filename is used for #line directives in the generated C.
func Generate(prog *syntax.Program, filename string) string {
	g := &generator{
		filename:  filename,
		funcCount: 0,
		tmpCount:  0,
		funcNames: make(map[string]string),
	}
	return g.generate(prog)
}

type generator struct {
	filename  string
	funcCount int               // counter for unique function names
	tmpCount  int               // counter for unique temp variable names
	funcNames map[string]string // maps Monk variable name → hoisted C function name
	funcs     strings.Builder   // collected function definitions (hoisted above main)
	body      strings.Builder   // main body statements
}

// newTemp returns a unique C temp variable name.
func (g *generator) newTemp() string {
	g.tmpCount++
	return fmt.Sprintf("_tmp_%d", g.tmpCount)
}

func (g *generator) generate(prog *syntax.Program) string {
	var out strings.Builder

	// Header with #line for source mapping
	out.WriteString("/* Generated by Monk Lang compiler */\n")
	// cString() handles escaping for Windows paths, quotes, etc.
	fmt.Fprintf(&out, "#line 1 %s\n", cString(g.filename))
	out.WriteString("#include \"runtime.h\"\n")
	out.WriteString("#include <stdlib.h>\n")
	out.WriteString("#include <string.h>\n\n")

	// Emit all statements (functions get hoisted, rest goes to main body)
	for _, stmt := range prog.Stmts {
		g.emitStmt(stmt)
	}

	// Emit hoisted functions
	out.WriteString(g.funcs.String())

	// Emit main
	out.WriteString("int main(void) {\n")
	out.WriteString(g.body.String())
	out.WriteString("    return 0;\n")
	out.WriteString("}\n")

	return out.String()
}

// --- Statement emission ---

func (g *generator) emitStmt(stmt syntax.Stmt) {
	switch s := stmt.(type) {
	case *syntax.VarDeclStmt:
		g.emitVarDecl(s)
	case *syntax.AssignStmt:
		g.emitAssign(s)
	case *syntax.ExprStmt:
		g.emitLine("    %s;\n", g.emitExpr(s.Expr))
	case *syntax.IfStmt:
		g.emitIf(s)
	case *syntax.WhileStmt:
		g.emitWhile(s)
	case *syntax.ForStmt:
		g.emitFor(s)
	case *syntax.ReturnStmt:
		g.emitReturn(s)
	case *syntax.BreakStmt:
		g.emitLine("    break;\n")
	case *syntax.ContinueStmt:
		g.emitLine("    continue;\n")
	case *syntax.GuardStmt:
		g.emitGuard(s)
	case *syntax.BlockStmt:
		for _, inner := range s.Stmts {
			g.emitStmt(inner)
		}
	default:
		g.emitLine("    /* TODO: unhandled statement %T */\n", stmt)
	}
}

func (g *generator) emitVarDecl(s *syntax.VarDeclStmt) {
	// Function declarations: hoist the C function, track the name mapping
	if fnExpr, isFn := s.Value.(*syntax.FuncExpr); isFn {
		g.funcCount++
		cFuncName := fmt.Sprintf("_monk_func_%d", g.funcCount)
		g.funcNames[s.Name] = cFuncName
		g.hoistFunction(cFuncName, fnExpr)
		return
	}

	value := g.emitExpr(s.Value)
	g.emitLine("    MonkValue %s = monk_deep_copy(%s);\n", mangleName(s.Name), value)
}

func (g *generator) emitAssign(s *syntax.AssignStmt) {
	value := g.emitExpr(s.Value)

	switch target := s.Target.(type) {
	case *syntax.IdentExpr:
		name := mangleName(target.Name)
		tmp := g.newTemp()
		switch s.Op {
		case syntax.Equal:
			// Compute new value BEFORE freeing old (avoids use-after-free
			// when the new value expression references the variable)
			g.emitLine("    { MonkValue %s = monk_deep_copy(%s);\n", tmp, value)
			g.emitLine("      monk_free(%s);\n", name)
			g.emitLine("      %s = %s; }\n", name, tmp)
		case syntax.PlusEqual:
			// += mirrors Plus: dispatch on MONK_STRING for the concat overload
			// so `s += "world"` on a string routes through monk_string_concat
			// instead of monk_add (which would runtime-error).
			g.emitLine("    { MonkValue %s = (%s.kind==MONK_STRING ? monk_string_concat(%s,%s) : monk_add(%s,%s));\n",
				tmp, name, name, value, name, value)
			g.emitLine("      monk_free(%s);\n", name)
			g.emitLine("      %s = %s; }\n", name, tmp)
		default:
			op := compoundToArith(s.Op)
			g.emitLine("    { MonkValue %s = %s(%s, %s);\n", tmp, op, name, value)
			g.emitLine("      monk_free(%s);\n", name)
			g.emitLine("      %s = %s; }\n", name, tmp)
		}
	case *syntax.IndexExpr:
		obj := g.emitExpr(target.Object)
		idx := g.emitExpr(target.Index)
		g.emitLine("    monk_array_set(&%s, %s, %s);\n", obj, idx, value)
	case *syntax.PropertyExpr:
		obj := g.emitExpr(target.Object)
		g.emitLine("    monk_record_set(&%s, \"%s\", %s);\n", obj, target.Property, value)
	}
}

// emitIf handles if/else-if/else chains recursively.
func (g *generator) emitIf(s *syntax.IfStmt) {
	cond := g.emitExpr(s.Condition)
	g.emitLine("    if (monk_is_truthy(%s)) {\n", cond)
	for _, stmt := range s.Then.Stmts {
		g.emitStmt(stmt)
	}
	if s.Else != nil {
		switch e := s.Else.(type) {
		case *syntax.BlockStmt:
			g.emitLine("    } else {\n")
			for _, stmt := range e.Stmts {
				g.emitStmt(stmt)
			}
			g.emitLine("    }\n")
			return
		case *syntax.IfStmt:
			// Recursive: handles arbitrary else-if chain depth
			g.body.WriteString("    } else ")
			g.emitIfInline(e)
			return
		}
	}
	g.emitLine("    }\n")
}

// emitIfInline emits an if statement without the leading indent (for else-if chains).
func (g *generator) emitIfInline(s *syntax.IfStmt) {
	cond := g.emitExpr(s.Condition)
	fmt.Fprintf(&g.body, "if (monk_is_truthy(%s)) {\n", cond)
	for _, stmt := range s.Then.Stmts {
		g.emitStmt(stmt)
	}
	if s.Else != nil {
		switch e := s.Else.(type) {
		case *syntax.BlockStmt:
			g.emitLine("    } else {\n")
			for _, stmt := range e.Stmts {
				g.emitStmt(stmt)
			}
			g.emitLine("    }\n")
			return
		case *syntax.IfStmt:
			g.body.WriteString("    } else ")
			g.emitIfInline(e)
			return
		}
	}
	g.emitLine("    }\n")
}

func (g *generator) emitWhile(s *syntax.WhileStmt) {
	cond := g.emitExpr(s.Condition)
	g.emitLine("    while (monk_is_truthy(%s)) {\n", cond)
	for _, stmt := range s.Body.Stmts {
		g.emitStmt(stmt)
	}
	g.emitLine("    }\n")
}

func (g *generator) emitFor(s *syntax.ForStmt) {
	iter := g.emitExpr(s.Iterable)
	varName := mangleName(s.VarName)

	g.emitLine("    {\n")
	g.emitLine("        MonkValue _iter = %s;\n", iter)
	g.emitLine("        if (_iter.kind == MONK_ARRAY) {\n")
	g.emitLine("            for (int64_t _i = 0; _i < _iter.array_val->length; _i++) {\n")
	g.emitLine("                MonkValue %s = monk_deep_copy(_iter.array_val->data[_i]);\n", varName)
	for _, stmt := range s.Body.Stmts {
		g.emitStmt(stmt)
	}
	g.emitLine("                monk_free(%s);\n", varName)
	g.emitLine("            }\n")
	g.emitLine("        } else if (_iter.kind == MONK_STRING) {\n")
	g.emitLine("            for (int64_t _i = 0; _iter.str_val[_i]; ) {\n")
	g.emitLine("                int64_t _clen = 1;\n")
	// Fix 6: bounds check for malformed UTF-8
	g.emitLine("                while (_iter.str_val[_i + _clen] && (_iter.str_val[_i + _clen] & 0xC0) == 0x80) _clen++;\n")
	g.emitLine("                char *_ch = malloc(_clen + 1);\n")
	g.emitLine("                memcpy(_ch, _iter.str_val + _i, _clen);\n")
	g.emitLine("                _ch[_clen] = '\\0';\n")
	g.emitLine("                MonkValue %s = (MonkValue){.kind = MONK_STRING, .str_val = _ch};\n", varName)
	for _, stmt := range s.Body.Stmts {
		g.emitStmt(stmt)
	}
	g.emitLine("                free(_ch);\n")
	g.emitLine("                _i += _clen;\n")
	g.emitLine("            }\n")
	g.emitLine("        }\n")
	g.emitLine("    }\n")
}

func (g *generator) emitReturn(s *syntax.ReturnStmt) {
	if s.Value == nil {
		g.emitLine("    return monk_none();\n")
	} else {
		g.emitLine("    return %s;\n", g.emitExpr(s.Value))
	}
}

func (g *generator) emitGuard(s *syntax.GuardStmt) {
	varName := mangleName(s.VarName)
	errName := mangleName(s.ErrorName)

	g.emitLine("    MonkValue %s = monk_none();\n", varName)
	g.emitLine("    {\n")
	g.emitLine("        MonkGuardContext _guard_ctx;\n")
	g.emitLine("        if (monk_guard_begin(&_guard_ctx) == 0) {\n")
	g.emitLine("            %s = %s;\n", varName, g.emitExpr(s.Expr))
	g.emitLine("            monk_guard_end(&_guard_ctx);\n")
	g.emitLine("        } else {\n")
	g.emitLine("            MonkValue %s = monk_current_error();\n", errName)
	for _, stmt := range s.Against.Stmts {
		g.emitStmt(stmt)
	}
	g.emitLine("            (void)%s;\n", errName)
	g.emitLine("        }\n")
	g.emitLine("    }\n")
}

// --- Expression emission ---
// Each returns a C expression string that evaluates to a MonkValue.

func (g *generator) emitExpr(expr syntax.Expr) string {
	switch e := expr.(type) {
	case *syntax.NumberExpr:
		if e.IsInt {
			return fmt.Sprintf("monk_int(%s)", e.Value)
		}
		return fmt.Sprintf("monk_float(%s)", e.Value)

	case *syntax.StringExpr:
		return fmt.Sprintf("monk_string(%s)", cString(e.Value))

	case *syntax.TemplateExpr:
		return fmt.Sprintf("monk_string(%s)", cString(e.Value))

	case *syntax.BoolExpr:
		if e.Value {
			return "monk_bool(true)"
		}
		return "monk_bool(false)"

	case *syntax.NoneExpr:
		return "monk_none()"

	case *syntax.IdentExpr:
		return mangleName(e.Name)

	case *syntax.UnaryExpr:
		operand := g.emitExpr(e.Operand)
		switch e.Op {
		case syntax.Minus:
			return fmt.Sprintf("monk_neg(%s)", operand)
		case syntax.Not, syntax.Bang:
			return fmt.Sprintf("monk_bool(!monk_is_truthy(%s))", operand)
		case syntax.Tilde:
			return fmt.Sprintf("monk_int(~(%s).int_val)", operand)
		}

	case *syntax.BinaryExpr:
		return g.emitBinary(e)

	case *syntax.CallExpr:
		return g.emitCall(e)

	case *syntax.IndexExpr:
		// Fix 7: evaluate object once to avoid double evaluation
		obj := g.emitExpr(e.Object)
		idx := g.emitExpr(e.Index)
		tmpObj := g.newTemp()
		tmpIdx := g.newTemp()
		return fmt.Sprintf("({MonkValue %s=%s; MonkValue %s=%s; "+
			"%s.kind==MONK_STRING ? monk_string_index(%s,%s) : monk_array_get(%s,%s);})",
			tmpObj, obj, tmpIdx, idx,
			tmpObj, tmpObj, tmpIdx, tmpObj, tmpIdx)

	case *syntax.PropertyExpr:
		obj := g.emitExpr(e.Object)
		return fmt.Sprintf("monk_record_get(%s, \"%s\")", obj, e.Property)

	case *syntax.ArrayExpr:
		if len(e.Elements) == 0 {
			return "monk_array(NULL, 0)"
		}
		elems := make([]string, len(e.Elements))
		for i, elem := range e.Elements {
			elems[i] = g.emitExpr(elem)
		}
		return fmt.Sprintf("monk_array((MonkValue[]){%s}, %d)", strings.Join(elems, ", "), len(elems))

	case *syntax.RecordExpr:
		if len(e.Fields) == 0 {
			return "monk_record(NULL, 0)"
		}
		fields := make([]string, len(e.Fields))
		for i, f := range e.Fields {
			fields[i] = fmt.Sprintf("{.key = %s, .value = %s}", cString(f.Key), g.emitExpr(f.Value))
		}
		return fmt.Sprintf("monk_record((MonkRecordField[]){%s}, %d)", strings.Join(fields, ", "), len(fields))

	case *syntax.FuncExpr:
		return g.emitFuncExpr(e)

	case *syntax.ThrowExpr:
		val := g.emitExpr(e.Value)
		return fmt.Sprintf("(monk_throw(%s), monk_none())", val)
	}

	return "monk_none() /* unhandled expr */"
}

func (g *generator) emitBinary(e *syntax.BinaryExpr) string {
	left := g.emitExpr(e.Left)
	right := g.emitExpr(e.Right)

	switch e.Op {
	// Arithmetic
	case syntax.Plus:
		// Fix 2: evaluate left once to avoid double evaluation
		tmp := g.newTemp()
		return fmt.Sprintf("({MonkValue %s=%s; %s.kind==MONK_STRING ? monk_string_concat(%s,%s) : monk_add(%s,%s);})",
			tmp, left, tmp, tmp, right, tmp, right)
	case syntax.Minus:
		return fmt.Sprintf("monk_sub(%s, %s)", left, right)
	case syntax.Star:
		return fmt.Sprintf("monk_mul(%s, %s)", left, right)
	case syntax.Slash:
		return fmt.Sprintf("monk_div(%s, %s)", left, right)
	case syntax.Percent:
		return fmt.Sprintf("monk_mod(%s, %s)", left, right)

	// Comparison
	case syntax.EqualEqual, syntax.Is:
		return fmt.Sprintf("monk_equal(%s, %s)", left, right)
	case syntax.BangEqual:
		return fmt.Sprintf("monk_not_equal(%s, %s)", left, right)
	case syntax.Less:
		return fmt.Sprintf("monk_less(%s, %s)", left, right)
	case syntax.Greater:
		return fmt.Sprintf("monk_greater(%s, %s)", left, right)
	case syntax.LessEqual:
		return fmt.Sprintf("monk_less_equal(%s, %s)", left, right)
	case syntax.GreaterEqual:
		return fmt.Sprintf("monk_greater_equal(%s, %s)", left, right)

	// Logical (short-circuit via ternary)
	case syntax.And, syntax.AmpAmp:
		return fmt.Sprintf("(monk_is_truthy(%s) ? monk_bool(monk_is_truthy(%s)) : monk_bool(false))", left, right)
	case syntax.Or, syntax.PipePipe:
		return fmt.Sprintf("(monk_is_truthy(%s) ? monk_bool(true) : monk_bool(monk_is_truthy(%s)))", left, right)

	// Bitwise — direct C operators on int values
	case syntax.Amp:
		return fmt.Sprintf("monk_int((%s).int_val & (%s).int_val)", left, right)
	case syntax.Pipe:
		return fmt.Sprintf("monk_int((%s).int_val | (%s).int_val)", left, right)
	case syntax.Caret:
		return fmt.Sprintf("monk_int((%s).int_val ^ (%s).int_val)", left, right)
	case syntax.ShiftLeft:
		return fmt.Sprintf("monk_int((%s).int_val << (%s).int_val)", left, right)
	case syntax.ShiftRight:
		return fmt.Sprintf("monk_int((%s).int_val >> (%s).int_val)", left, right)
	}

	return fmt.Sprintf("monk_none() /* unhandled op %s */", e.Op)
}

func (g *generator) emitCall(e *syntax.CallExpr) string {
	args := make([]string, len(e.Args))
	for i, arg := range e.Args {
		args[i] = g.emitExpr(arg)
	}
	argStr := strings.Join(args, ", ")

	if ident, ok := e.Callee.(*syntax.IdentExpr); ok {
		// Known builtin → direct C runtime call
		if fn, ok := builtinMap[ident.Name]; ok {
			return fmt.Sprintf("%s(%s)", fn, argStr)
		}

		// User-defined function → call the hoisted C function
		if cName, ok := g.funcNames[ident.Name]; ok {
			return fmt.Sprintf("%s(%s)", cName, argStr)
		}

		// Unknown — forward reference or passed-in function
		return fmt.Sprintf("%s(%s)", mangleName(ident.Name), argStr)
	}

	return "monk_none() /* indirect call TODO */"
}

// hoistFunction emits a C function definition into the hoisted funcs buffer.
func (g *generator) hoistFunction(cName string, e *syntax.FuncExpr) {
	params := make([]string, len(e.Params))
	for i, p := range e.Params {
		params[i] = fmt.Sprintf("MonkValue %s", mangleName(p.Name))
	}

	paramStr := strings.Join(params, ", ")
	if paramStr == "" {
		paramStr = "void"
	}

	fmt.Fprintf(&g.funcs, "static MonkValue %s(%s) {\n", cName, paramStr)

	// Emit body into funcs buffer (swap body temporarily)
	savedBody := g.body
	g.body = strings.Builder{}
	for _, stmt := range e.Body.Stmts {
		g.emitStmt(stmt)
	}
	g.funcs.WriteString(g.body.String())
	g.body = savedBody

	g.funcs.WriteString("    return monk_none();\n")
	g.funcs.WriteString("}\n\n")
}

func (g *generator) emitFuncExpr(e *syntax.FuncExpr) string {
	// Anonymous function expression — hoist it
	g.funcCount++
	cName := fmt.Sprintf("_monk_func_%d", g.funcCount)
	g.hoistFunction(cName, e)
	return "monk_none() /* anonymous func */"
}

// --- Helpers ---

func (g *generator) emitLine(format string, args ...any) {
	fmt.Fprintf(&g.body, format, args...)
}

// mangleName prefixes Monk variable names to avoid C keyword collisions.
func mangleName(name string) string {
	return "mk_" + name
}

// cString returns a C string literal with proper escaping.
func cString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	s = strings.ReplaceAll(s, "\t", "\\t")
	return "\"" + s + "\""
}

// Fix 3: panic on unknown compound operator instead of silent fallback
func compoundToArith(op syntax.TokenKind) string {
	switch op {
	case syntax.PlusEqual:
		return "monk_add"
	case syntax.MinusEqual:
		return "monk_sub"
	case syntax.StarEqual:
		return "monk_mul"
	case syntax.SlashEqual:
		return "monk_div"
	case syntax.PercentEqual:
		return "monk_mod"
	default:
		panic(fmt.Sprintf("codegen: unhandled compound operator: %s", op))
	}
}

// builtinMap maps Monk builtin names to C runtime function names.
var builtinMap = map[string]string{
	"show":          "monk_show",
	"to_string":     "monk_to_string",
	"to_int":        "monk_to_int",
	"to_float":      "monk_to_float",
	"length":        "monk_length",
	"substring":     "monk_substring",
	"index_of":      "monk_index_of",
	"split":         "monk_split",
	"trim":          "monk_trim",
	"to_upper_case": "monk_to_upper_case",
	"to_lower_case": "monk_to_lower_case",
	"append":        "monk_append",
	"prepend":       "monk_prepend",
	"pop":           "monk_pop",
	"drop":          "monk_drop",
	"take":          "monk_take",
	"slice":         "monk_slice",
	"range":         "monk_range",
	"abs":           "monk_abs",
	"floor":         "monk_floor",
	"ceil":          "monk_ceil",
	"round":         "monk_round",
	"sqrt":          "monk_sqrt",
	"pow":           "monk_pow",
	"log":           "monk_log",
	"log10":         "monk_log10",
	"exp":           "monk_exp",
	"min":           "monk_min",
	"max":           "monk_max",
	"sin":           "monk_sin",
	"cos":           "monk_cos",
	"tan":           "monk_tan",
	"asin":          "monk_asin",
	"acos":          "monk_acos",
	"atan":          "monk_atan",
	"typeof":        "monk_typeof",
	"is_number":     "monk_is_number",
	"is_string":     "monk_is_string",
	"is_boolean":    "monk_is_boolean",
	"is_array":      "monk_is_array",
	"is_record":     "monk_is_record",
	"is_function":   "monk_is_function",
	"is_none":       "monk_is_none",
	"file_read":     "monk_file_read",
	"file_write":    "monk_file_write",
	"file_exists":   "monk_file_exists",
	"env_get":       "monk_env_get",
	"exit":          "monk_exit",
}
